### ISSUE TITLE
Proposal on API improvements

### ISSUE THREAD

**Issue by bcardarella** [danschultzer/test_server#31]
Thank you for this library, it's certainly the way I want to be testing network requests. Especially that you have WS covered.

Would you be open to a proposal of a few API changes:

* `method` instead of `via` to better align with HTTP spec nomenclature
* a pipeline-like DSL for chaining multiple plugs together for request processing
* extending the plug pipeline for WS connections

Specifically I need to set headers on initial WS connections. From what I can tell this is currently not supported.

**Comment by danschultzer** [comment]
Thanks for the proposals @bcardarella!

> - `method` instead of via to better align with HTTP spec nomenclature

I'm tying TestServer API closely to Plug, so I'm using the same options as `Plug.Router` match  (`:via`, `:match`, `:to`) : https://hexdocs.pm/plug/Plug.Router.html#match/3

Maybe `:method` makes more sense, but the idea is to make it as 1:1 as possible with how you usually set up plug routes.

> - a pipeline-like DSL for chaining multiple plugs together for request processing

Do you mean chaining plugs for a single request expectation or chaining multiple request expectations together? Can you show me an example of how this DSL would look/work?

> - extending the plug pipeline for WS connections
>
> Specifically I need to set headers on initial WS connections. From what I can tell this is currently not supported.

What headers do you need to set? TestServer calls [`Plug.Conn.upgrade_adapter/3`](https://hexdocs.pm/plug/Plug.Conn.html#upgrade_adapter/3) and let the web server handle the handshake. IIRC there isn't a way to set response headers as the web server (e.g. Bandit) takes over the handshake process.

If you want to assert on request headers then you can use the regular plug assertions:

```elixir
TestServer.add("/ws", to: fn conn ->
  assert Plug.Conn.get_req_header(conn, "upgrade") == ["websocket"]
  assert Plug.Conn.get_req_header(conn, "connection") == ["Upgrade"]

  Plug.Conn.resp(conn, 403, "Request assertion")
end)
```

**Comment by bcardarella** [comment]
> I'm tying TestServer API closely to Plug

that's fair

> Do you mean chaining plugs for a single request expectation

chaining multiple plugs for a single inbound request similar to what you'd do with `pipeline` in Phoenix. But based upon your last example I guess it is better to assert the request shape in isolation than through a pipeline.

> IIRC there isn't a way to set response headers

Correct, this is for inbound request headers that would be used for asserting if the request is valid. For example, in LiveView Native we are looking to move over to `ACCEPT` header and move away from url query param. This is perfectly fine for initial WS connection. Based upon `ACCEPT` value the response should be unique.

>  If you want to assert on request headers then you can use the regular plug assertions

This seems ok, I haven't looked at the implementation but was hoping to do it as a single pass rather than set up two separate tests. (one pre-ws upgrade, one post-ws upgrade)

**Comment by danschultzer** [comment]
I see, yeah, I think there's a good reason to have a way to assert on the handshake request with `websocket_init/2`, e.g. testing with invalid responses. `websocket_init/2` essentially works the same as `add/2` with only a custom `:to` option set, so I could allow `:to` to be overridden to allow for custom handling.

I'll take a look at it.

**Comment by danschultzer** [comment]
This should resolve the issue with assertion in one pass for websockets: #35

**Comment by Nezteb** [comment]
Are there any other proposed API improvements from this issue still under consideration? Or should it be closed? Just curious!
